---
title: "MicroProfile 7.1"
date: 2025-05-06
summary: "MicroProfile 7.1 Release Plan"
---



MicroProfile follows a train model for its Platform releases. MicroProfile releases include component specifications that are ready and have been approved. The specifications in MicroProfile 7.1 include:

 

* Config 3.1

* Fault Tolerance 4.1

* Health 4.0

* JWT RBAC 2.1

* OpenAPI 4.1*

* Rest Client 4.0

* Telemetry 2.1*

 

pass:[*] - New or Updated

 

Jakarta EE 10 Core Profile includes the following specifications, which must be implemented by MicroProfile 7.1 implementations:

 

* Jakarta Annotations 2.1

* Jakarta Contexts and Dependency Injection (Lite Section) 4.0**

* Jakarta Dependency Injection 2.0

* Jakarta Interceptors 2.1

* Jakarta JSON Binding 3.0

* Jakarta JSON Processing 2.1

* Jakarta RESTful Web Services 3.1

 

pass:[**] Full CDI support is not required. CDI SE support is not required.

Release plan is https://projects.eclipse.org/projects/technology.microprofile/releases/microprofile-7.1[here].

# Ballots

== Plan Review
The Specification Committee Ballot concluded successfully on The Specification Committee Ballot concluded successfully on YYYY-MM-DD with the results documented in the https://www.eclipse.org/lists/microprofile-wg/msg02466.html[microprofile-wg mailing list].

== Release Review
The Specification Committee Ballot concluded successfully on YYYY-MM-DD with the results documented in the https://www.eclipse.org/lists/microprofile-wg/msg02607.html[microprofile-wg mailing list]
