---
title: "MicroProfile 7.2"
date: 2026-07-21
summary: 
---
MicroProfile follows a train model for its Platform releases. MicroProfile releases include component specifications that are ready and have been approved. The specifications in MicroProfile 7.2 include:

* Config 3.1
* Fault Tolerance 4.1
* Health 4.0
* JWT RBAC 2.2*
* OpenAPI 4.2*
* Rest Client 4.0
* Telemetry 2.2*
 
pass:[*] - New or Updated

MicroProfile 7.2 requires the minimum Jakarta EE 10 Core Profile. An implementation is not restricted by the minimum requirement. An implementation may choose to support Jakarta EE 11 Core Profile instead. 

Jakarta EE 10 or Jakarta EE 11 Core Profile includes the following specifications:

Jakarta EE 10

* Jakarta Annotations 2.1
* Jakarta Contexts and Dependency Injection (Lite Section) 4.0**
* Jakarta Dependency Injection 2.0
* Jakarta Interceptors 2.1
* Jakarta JSON Binding 3.0
* Jakarta JSON Processing 2.1
* Jakarta RESTful Web Services 3.1

Jakarta EE 11

* Jakarta Annotations 3.0*
* Jakarta Contexts and Dependency Injection (Lite Section) 4.1**
* Jakarta Dependency Injection 2.0
* Jakarta Interceptors 2.2*
* Jakarta JSON Binding 3.0
* Jakarta JSON Processing 2.1
* Jakarta RESTful Web Services 4.0*

pass:[**] Full CDI support is not required. CDI SE support is not required.

* https://projects.eclipse.org/projects/technology.microprofile/releases/microprofile-7.2[MicroProfile 7.2 Release Record]

# Ballots

== Plan Review

The Specification Committee Ballot concluded successfully on xxx with the results documented in the https://www.eclipse.org/lists/microprofile-wg/msgxxx.html[microprofile-wg mailing list].

== Release Review
The Specification Committee Ballot concluded successfully on xxx with the results documented in the https://www.eclipse.org/lists/microprofile-wg/msgxxx.html[microprofile-wg mailing list]
